### ISSUE TITLE
Can this do what @BigTechAlerts does or it's just for my mutuals?

### ISSUE THREAD

**Issue by danidamiobi** [Kyu/follower-tracker#1]
Thanks for putting such an amazing tool as this up.  I would love to know if the followers it tracks are just my mutuals or I could set it for other accounts like @BigTechAlerts on Twitter.

**Comment by Kyu** [comment]
Hey Dami. Right now it only tracks your current mutuals. I can update the readme to reflect that, but the tech alerts feature can be added in a future update, if that's something you'd like

**Comment by Kyu** [comment]
I've added an event bus in 7cd00d83c422a7fd46c162acf39d9384cbc82b9e, as well new config options that allow you to define other users to be tracked in e1e048868091ee0c8a4890f1b0ed426b852b7b2d. I'll close this if you don't have any other questions.
